### ISSUE TITLE
the Contacts section header and initial test should start below the photo 

### ISSUE THREAD

**Issue by aaaashy** [marklacey1966/joint-snoose#12]
the Contacts section header and initial test should start below the photo named "Memories of Snoose-Boulevard"

**Comment by marklacey1966** [comment]
The pictures at the top of the Resources and Contacts section are to become banners rather than stand alone pictures. The titles Resources and Contacts need to be centered in the picture and in white text. Good luck!

**Comment by aaaashy** [comment]
has been dealt with
