### ISSUE TITLE
Image missing for Contacts section

### ISSUE THREAD

**Issue by 5jt** [marklacey1966/joint-snoose#15]

**Comment by sowiczowicz** [comment]
I don't see any image on your original website. So which one are you referring to?

**Comment by 5jt** [comment]
https://snooseboulevard.files.wordpress.com/2018/06/harvey-and-bernstein-002.png?w=800&#038;h=570&#038;crop=1

visible at https://snooseboulevard.org/contact/

**Comment by sowiczowicz** [comment]
Of course, I didn't notice the banner had changed


-----Original Message-----

**Comment by 5jt** [comment]
Closed by commit 5fbda6818858664650b8c084039e85eb6875b066
