### ISSUE TITLE
Images overflow the right margin

### ISSUE THREAD

**Issue by 5jt** [marklacey1966/joint-snoose#20]
They should fit within the left and right margins of the `wrapper` div.

Hint: The `img` HTML element is an _inline_ element. That means it gets rendered as if it were a single (big!) character, and block properties (e.g. border, width, margin, etc.) cannot be set for it. To set block properties, make it the child of a block element, such as a div, and set the block properties of that.

**Comment by marklacey1966** [comment]
Thanks for the hint Stephen. And thanks for today’s lesson, it was very useful and enjoyable. Have a good weekend. Mark

Sent from my iPad

On 16 Oct 2020, at 15:17, Stephen Taylor <notifications@github.com> wrote:

﻿

They should fit within the left and right margins of the wrapper div.

Hint: The img HTML element is an inline element. That means it gets rendered as if it were a single (big!) character, and block properties (e.g. border, width, margin, etc.) cannot be set for it. To set block properties, make it the child of a block element, such as a div, and set the block properties of that.

**Comment by marklacey1966** [comment]
I think this moght have sorted the problem. More trial and error than any knowledge of what I'm doing
